---
local_route: 127.0.0.1
pid_filename: /tmp/http_backend.pid
nats_uri: nats://localhost:4222/

logging:
  level: debug

# Global Configuration for each backend servers
monitor_interval: 5
auto_start: true    # start the backend when it is down.
listen_delay: 2
stop_on_exit: true  # stop the backend when http_backend stops.
#
# Backend HTTP servers to be registered.
#
backend_servers:
  - name: "mock-server"
    domain: "foo.vcap.me"
    port: 8080
    pid_filename: "/tmp/http_backend_agent/mock-server-55737.pid"
    start: "/Users/yssk22/Dropbox/vcap-http-backend/spec/fixtures/start_server.rb -p 55737 -P /tmp/http_backend_agent/mock-server-55737.pid"
    stop:  "kill $(cat /tmp/http_backend_agent/mock-server-55737.pid)"

status:
  port: 34501
  user: thin
  password: thin